name: Actualizar CSV automáticamente

on:
  # Ejecuta el workflow según un cron (en este ejemplo, diariamente a medianoche UTC)
  schedule:
    - cron: "0 0 * * *"
  # Permite ejecuciones manuales desde la pestaña Actions en GitHub
  workflow_dispatch:

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install pandas

      # (Opcional) Si tienes tests, puedes ejecutarlos. Si no, puedes omitir o usar pytest || true.
      #- name: Run pytest
      #  run: pytest || true

      - name: Ejecutar script para generar CSV
        run: python prueba_azure.py

      - name: Hacer commit y push del CSV
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add sample_data.csv
          git commit -m "Actualización automática del CSV" || echo "No hay cambios para commitear"
          git push
